name: "repo access test"

description: "Testing repo access"
inputs:
  working_directory:
    requiered: true  
runs:
  using: "composite"
  steps:
    - name: get-info
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: python ${{ github.action_path }}/src/main.py
    - name: env
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: env 
    - name: workdir
      run: echo ${{ inputs.working_directory }}
      shell: bash
    
