name: "repo access test"

description: "Testing repo access"
inputs:
  working_directory:
    requiered: true
  output_path:
    requiered: true
    default: 'CLUSTERINFO.md'
runs:
  using: "composite"
  steps:
    - name: install-deps
      shell: bash
      run: pip install --no-cache-dir -r ${{ github.action_path }}/requirements.txt
    - name: get-info
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: python ${{ github.action_path }}/src/main.py --output_path ${{ inputs.output_path }}
    
